name: debugger-action
on:
  push:
    branches:
      - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup tmate session
      - uses: mxschmitt/action-tmate@v3
        timeout-minutes: 9999999999999999999999999999999
